name: Tests and Linting

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  gitlint:
    runs-on: ubuntu-latest
    name: GitLint
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install gitlint
        run: |
          python -m pip install gitlint

      - name: Run gitlint
        run: |
          # Lint everything from the base to the latest
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD" \
                  -c general.ignore-merge-commits=false                       \
                  -c general.ignore-fixup-commits=false                       \
                  -c general.ignore-fixup-amend-commits=false                 \
                  -c general.ignore-squash-commits=false                      \
                  -c general.contrib=contrib-disallow-cleanup-commits,contrib-title-conventional-commits,contrib-body-requires-signed-off-by \
                  -c title-must-not-contain-word.words=wip                    \
                  -C .gitlint
